on:  workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Run script
      run: |
        chmod +x ./generate.sh
        bash generate.sh
    - name: Commit and push
      run: |
        git diff
        git config --global user.email "action@github.com"
        git config --global user.name "Github action"
        git commit -am "updating adguard_hosts.txt" || exit 0
        git push