on:  workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run script
      run: |
        chmod +x ./generate.sh
        ./generate.sh
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Script results
        path: adguard_filtered.txt